"""
DUBFORGE Engine — __init__

All engine modules accessible from `from engine import *`
"""

from engine.phi_core import (
    PHI,
    FIBONACCI,
    generate_phi_core_v1,
    generate_phi_core_v2_wook,
    phi_harmonic_series,
    fibonacci_harmonic_series,
    write_wav,
    midi_to_freq,
    freq_to_midi,
)
from engine.rco import (
    Section,
    RCOProfile,
    phi_curve,
    fibonacci_step_curve,
    linear_curve,
    exponential_curve,
    generate_energy_curve,
    subtronics_weapon_preset,
    subtronics_emotive_preset,
    subtronics_hybrid_preset,
    plot_curve,
)
from engine.psbs import (
    BassLayer,
    PSBSPreset,
    phi_crossovers,
    default_psbs,
    weapon_psbs,
    wook_psbs,
    calculate_phase_coherence,
    render_psbs_cycle,
    export_preset as export_psbs_preset,
)
from engine.sb_analyzer import (
    Track as SBTrack,
    Album,
    SignatureVector,
    build_corpus,
    load_corpus,
    analyze_corpus,
    build_signature_vector,
    vip_delta_analysis,
)
from engine.trance_arp import (
    ArpNote,
    ArpPattern,
    fibonacci_rise_pattern,
    phi_spiral_pattern,
    golden_gate_pattern,
    pattern_to_midi_data,
    export_pattern as export_arp_pattern,
)
from engine.growl_resampler import (
    pitch_shift,
    waveshape_distortion,
    frequency_shift,
    comb_filter,
    bit_reduce,
    formant_filter,
    growl_resample_pipeline,
    generate_saw_source,
    generate_fm_source,
)
from engine.chord_progression import (
    build_progression,
    build_chord,
    ALL_PRESETS as CHORD_PRESETS,
)
from engine.ableton_live import (
    build_dubstep_session_template,
    build_arrangement_template,
    psbs_device_chain,
    generate_m4l_control_script,
    SESSION_PRESETS as ABLETON_PRESETS,
    LOM_REFERENCE,
)
from engine.serum2 import (
    Serum2Patch,
    build_dubstep_patches as serum2_dubstep_patches,
    build_init_template as serum2_init_template,
    SERUM2_ARCHITECTURE,
    phi_unison_detune,
    phi_envelope,
    phi_filter_cutoff,
    phi_fm_ratio,
)
from engine.dojo import (
    BeltRank,
    BeltLevel,
    ApproachPhase,
    ApproachStep,
    TechniqueType,
    DojoTechnique,
    RackZone,
    RackCategory,
    BELT_SYSTEM,
    THE_APPROACH,
    DOJO_TECHNIQUES,
    ARTIST_PROFILE,
    DOJO_PLATFORM,
    build_128_rack,
    build_dojo_session_template,
    phi_belt_progression,
    phi_approach_timing,
    phi_mudpie_recipe,
)
from engine.memory import (
    MemoryEngine,
    get_memory,
    phi_recency_score,
    phi_relevance,
)
from engine.log import get_logger
from engine.config_loader import (
    load_config,
    get_config_value,
    list_configs,
    validate_config,
    validate_all_configs,
)

__all__ = [
    # phi_core
    "PHI",
    "FIBONACCI",
    "generate_phi_core_v1",
    "generate_phi_core_v2_wook",
    "phi_harmonic_series",
    "fibonacci_harmonic_series",
    "write_wav",
    "midi_to_freq",
    "freq_to_midi",
    # rco
    "Section",
    "RCOProfile",
    "phi_curve",
    "fibonacci_step_curve",
    "linear_curve",
    "exponential_curve",
    "generate_energy_curve",
    "subtronics_weapon_preset",
    "subtronics_emotive_preset",
    "subtronics_hybrid_preset",
    "plot_curve",
    # psbs
    "BassLayer",
    "PSBSPreset",
    "phi_crossovers",
    "default_psbs",
    "weapon_psbs",
    "wook_psbs",
    "calculate_phase_coherence",
    "render_psbs_cycle",
    "export_psbs_preset",
    # sb_analyzer
    "SBTrack",
    "Album",
    "SignatureVector",
    "build_corpus",
    "load_corpus",
    "analyze_corpus",
    "build_signature_vector",
    "vip_delta_analysis",
    # trance_arp
    "ArpNote",
    "ArpPattern",
    "fibonacci_rise_pattern",
    "phi_spiral_pattern",
    "golden_gate_pattern",
    "pattern_to_midi_data",
    "export_arp_pattern",
    # growl_resampler
    "pitch_shift",
    "waveshape_distortion",
    "frequency_shift",
    "comb_filter",
    "bit_reduce",
    "formant_filter",
    "growl_resample_pipeline",
    "generate_saw_source",
    "generate_fm_source",
    # chord_progression
    "build_progression",
    "build_chord",
    "midi_to_freq",
    "CHORD_PRESETS",
    # ableton_live
    "build_dubstep_session_template",
    "build_arrangement_template",
    "psbs_device_chain",
    "generate_m4l_control_script",
    "ABLETON_PRESETS",
    "LOM_REFERENCE",
    # serum2
    "Serum2Patch",
    "serum2_dubstep_patches",
    "serum2_init_template",
    "SERUM2_ARCHITECTURE",
    "phi_unison_detune",
    "phi_envelope",
    "phi_filter_cutoff",
    "phi_fm_ratio",
    # dojo
    "BeltRank",
    "BeltLevel",
    "ApproachPhase",
    "ApproachStep",
    "TechniqueType",
    "DojoTechnique",
    "RackZone",
    "RackCategory",
    "BELT_SYSTEM",
    "THE_APPROACH",
    "DOJO_TECHNIQUES",
    "ARTIST_PROFILE",
    "DOJO_PLATFORM",
    "build_128_rack",
    "build_dojo_session_template",
    "phi_belt_progression",
    "phi_approach_timing",
    "phi_mudpie_recipe",
    # memory
    "MemoryEngine",
    "get_memory",
    "phi_recency_score",
    "phi_relevance",
    # log
    "get_logger",
    # config_loader
    "load_config",
    "get_config_value",
    "list_configs",
    "validate_config",
    "validate_all_configs",
]
