"""
DUBFORGE — Sample Pack Exporter  (Session 192)

Export organized sample packs with folder structure,
naming conventions, metadata, and README generation.
"""

import json
import os
import time
from dataclasses import dataclass

from engine.config_loader import PHI
CATEGORY_FOLDERS = [
    "Kicks", "Snares", "Hats", "Percussion", "Claps",
    "Bass", "Leads", "Pads", "FX", "Risers",
    "Impacts", "Vocals", "Textures", "Loops", "One-Shots",
]

NAMING_TEMPLATES = {
    "dubstep": "{pack}_{category}_{bpm}bpm_{key}_{index:03d}",
    "minimal": "{category}_{index:03d}",
    "detailed": "{pack}_{category}_{subcategory}_{bpm}bpm_{key}_{variation}_{index:03d}",
}


@dataclass
class SampleEntry:
    """Represents a sample in the pack."""
    source_path: str
    category: str
    subcategory: str = ""
    bpm: float = 140.0
    key: str = "C"
    variation: str = "A"

    def to_dict(self) -> dict:
        return {
            "source": self.source_path,
            "category": self.category,
            "subcategory": self.subcategory,
            "bpm": self.bpm,
            "key": self.key,
            "variation": self.variation,
        }


@dataclass
class PackConfig:
    """Configuration for a sample pack export."""
    name: str = "DUBFORGE Pack"
    version: str = "1.0"
    author: str = "DUBFORGE"
    description: str = "Dubstep sample pack crafted with PHI precision"
    bpm: float = 140.0
    key: str = "C"
    genre: str = "Dubstep"
    naming_style: str = "dubstep"
    include_readme: bool = True
    include_metadata: bool = True

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "version": self.version,
            "author": self.author,
            "description": self.description,
            "bpm": self.bpm,
            "key": self.key,
            "genre": self.genre,
        }


class SamplePackExporter:
    """Export organized sample packs."""

    def __init__(self, output_dir: str = "output/sample_packs"):
        self.output_dir = output_dir
        self.samples: list[SampleEntry] = []
        self.config = PackConfig()

    def configure(self, **kwargs) -> None:
        """Set pack configuration."""
        for k, v in kwargs.items():
            if hasattr(self.config, k):
                setattr(self.config, k, v)

    def add_sample(self, source: str, category: str, **kwargs) -> None:
        """Add a sample to the export list."""
        entry = SampleEntry(
            source_path=source,
            category=category,
            subcategory=kwargs.get("subcategory", ""),
            bpm=kwargs.get("bpm", self.config.bpm),
            key=kwargs.get("key", self.config.key),
            variation=kwargs.get("variation", "A"),
        )
        self.samples.append(entry)

    def _generate_filename(self, entry: SampleEntry, index: int) -> str:
        """Generate filename from naming template."""
        template = NAMING_TEMPLATES.get(
            self.config.naming_style,
            NAMING_TEMPLATES["dubstep"]
        )
        name = template.format(
            pack=self.config.name.replace(" ", "_"),
            category=entry.category,
            subcategory=entry.subcategory or "General",
            bpm=int(entry.bpm),
            key=entry.key,
            variation=entry.variation,
            index=index,
        )
        return f"{name}.wav"

    def _generate_readme(self) -> str:
        """Generate README for the pack."""
        categories: dict[str, int] = {}
        for s in self.samples:
            categories[s.category] = categories.get(s.category, 0) + 1

        lines = [
            f"# {self.config.name}",
            "",
            f"**Version:** {self.config.version}",
            f"**Author:** {self.config.author}",
            f"**Genre:** {self.config.genre}",
            f"**BPM:** {self.config.bpm}",
            f"**Key:** {self.config.key}",
            "",
            "## Description",
            "",
            self.config.description,
            "",
            "## Contents",
            "",
            f"Total samples: {len(self.samples)}",
            "",
        ]

        for cat, count in sorted(categories.items()):
            lines.append(f"- **{cat}**: {count} samples")

        lines.extend([
            "",
            "## Technical",
            "",
            "- Sample Rate: 44100 Hz",
            "- Bit Depth: 16-bit",
            f"- PHI Ratio: {PHI}",
            "- Tuning: A4 = 432 Hz",
            "",
            "*Generated by DUBFORGE v4.0.0*",
        ])

        return "\n".join(lines)

    def _generate_metadata(self) -> dict:
        """Generate pack metadata."""
        categories: dict[str, list[dict]] = {}
        for i, s in enumerate(self.samples):
            cat = s.category
            if cat not in categories:
                categories[cat] = []
            categories[cat].append({
                "filename": self._generate_filename(s, i + 1),
                **s.to_dict(),
            })

        return {
            "pack": self.config.to_dict(),
            "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
            "total_samples": len(self.samples),
            "categories": categories,
            "phi": PHI,
        }

    def export(self) -> dict:
        """Export the sample pack."""
        pack_dir = os.path.join(
            self.output_dir,
            self.config.name.replace(" ", "_")
        )
        os.makedirs(pack_dir, exist_ok=True)

        # Create category folders
        created_dirs: set[str] = set()
        exported: list[str] = []

        for i, sample in enumerate(self.samples):
            cat_dir = os.path.join(pack_dir, sample.category)
            if cat_dir not in created_dirs:
                os.makedirs(cat_dir, exist_ok=True)
                created_dirs.add(cat_dir)

            filename = self._generate_filename(sample, i + 1)
            dst = os.path.join(cat_dir, filename)

            # Copy if source exists, else create placeholder
            if os.path.exists(sample.source_path):
                import shutil
                shutil.copy2(sample.source_path, dst)
            else:
                # Create minimal WAV placeholder
                _write_placeholder(dst)

            exported.append(dst)

        # README
        if self.config.include_readme:
            readme_path = os.path.join(pack_dir, "README.md")
            with open(readme_path, "w") as f:
                f.write(self._generate_readme())

        # Metadata
        if self.config.include_metadata:
            meta_path = os.path.join(pack_dir, "metadata.json")
            with open(meta_path, "w") as f:
                json.dump(self._generate_metadata(), f, indent=2)

        return {
            "pack_dir": pack_dir,
            "exported": len(exported),
            "categories": len(created_dirs),
            "files": exported,
        }

    def get_summary(self) -> dict:
        """Get current pack summary."""
        categories: dict[str, int] = {}
        for s in self.samples:
            categories[s.category] = categories.get(s.category, 0) + 1
        return {
            "name": self.config.name,
            "total_samples": len(self.samples),
            "categories": categories,
        }


def _write_placeholder(path: str) -> None:
    """Write minimal placeholder WAV."""
    import struct
    import wave
    sr = 44100
    n = 4410  # 0.1s
    samples = [0] * n
    with wave.open(path, "w") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sr)
        data = struct.pack(f"<{n}h", *samples)
        wf.writeframes(data)


def create_dubstep_pack(output_dir: str = "output/sample_packs") -> dict:
    """Create a default dubstep sample pack structure."""
    exporter = SamplePackExporter(output_dir)
    exporter.configure(
        name="DUBFORGE Dubstep Vol 1",
        genre="Dubstep",
        bpm=140,
        key="F",
    )

    categories = {
        "Bass": 8,
        "Kicks": 5,
        "Snares": 5,
        "Hats": 4,
        "FX": 6,
        "Risers": 3,
        "Impacts": 3,
    }

    for cat, count in categories.items():
        for i in range(count):
            exporter.add_sample(
                source=f"placeholder_{cat}_{i}",
                category=cat,
                variation=chr(65 + i),
            )

    return exporter.export()


def main() -> None:
    print("Sample Pack Exporter")

    result = create_dubstep_pack()
    print(f"  Exported: {result['exported']} samples")
    print(f"  Categories: {result['categories']}")
    print(f"  Dir: {result['pack_dir']}")
    print("Done.")


if __name__ == "__main__":
    main()
